WIP: Recursive indexing
nlnwa/gowarc pull request #12
Opened 2020-12-17 12:15 UTC by Avokadoen

A bit bad practice, but to avoid creating hundreds of PRs I also include some minor refactors

2020-12-17 12:15 UTC, Avokadoen commented
Draft for issue #11

2020-12-28 14:31 UTC, maeb requested changes

2020-12-28 14:31 UTC, maeb commented on pkg/index/autoindex.go
> +						log.Error(err)
```suggestion
						log.Error(err)
						continue
```

2020-12-28 14:31 UTC, maeb commented on pkg/index/autoindex.go
> +func NewAutoIndexer(db *Db, watchDepth int) *autoindexer {
warcdir slice as argument

2020-12-28 14:31 UTC, maeb commented on pkg/index/autoindex.go
>  		log.Fatal(err)
Describe error

2020-12-28 14:31 UTC, maeb commented on pkg/index/autoindex.go
> +		log.Fatal(err)
Describe error

2020-12-29 12:41 UTC, maeb requested changes

2020-12-29 12:41 UTC, maeb commented on pkg/index/autoindex.go
> +		log.Fatalf("Failed to watch on path: %v, error: v%", path, err)
```
log.Fatalf("Failed to watch %v: %v", path, err)
```

2020-12-29 12:41 UTC, maeb commented on pkg/index/autoindex.go
> +		log.Fatalf("Failed to open file at: %v, error: %v", path, err)
```
log.Fatalf("Failed to open file %v: %v", path, err)
```

2020-12-29 12:41 UTC, maeb commented on pkg/index/autoindex.go
> +		log.Fatalf("%Failed to read directory. Name: %v, error: %v", f.Name(), err)
```
log.Fatalf("Failed to read directory %v: %v", f.Name(), err)
```

2020-12-29 12:46 UTC, maeb approved these changes

2020-12-29 12:50 UTC, merged